#!/bin/sh
# Writes vmauth-cloudflare's routing config. vmauth acts as a pure routing proxy;
# JWT auth is enforced by cloudflared (required:true + audTag) and Cloudflare
# Access at the edge. vmauth's jwt: users cannot be used here because vmauth
# always requires Authorization: Bearer prefix, which cloudflared never sets.
set -eu

: "${CLOUDFLARE_TEAM_DOMAIN:?Set CLOUDFLARE_TEAM_DOMAIN, the <team> in <team>.cloudflareaccess.com, from Zero Trust > Settings > Custom Pages.}"
: "${CLOUDFLARE_ACCESS_AUD:?Set CLOUDFLARE_ACCESS_AUD, the Access applications Audience (AUD) tag, from the applications Overview tab in Zero Trust.}"

OUT="${OUT_FILE:-/out/vmauth-cloudflare.yml}"

{
  echo "# Generated by docker/fetch-cloudflare-certs.sh — do not edit by hand."
  echo "# vmauth acts as a routing proxy; JWT auth is enforced by cloudflared."
  echo "# Team: ${CLOUDFLARE_TEAM_DOMAIN}  AUD: ${CLOUDFLARE_ACCESS_AUD}"
  echo "unauthorized_user:"
  echo "  url_prefix: \"http://console-cloudflare:3000/\""
} >"$OUT"

echo "Wrote ${OUT}:" >&2
cat "$OUT" >&2
